apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2024-09-09T18:12:48Z"
  generation: 1
  name: sourcesidentifiers.openappsec.io
  resourceVersion: "1371"
  uid: b2c0bc6d-7a08-4041-ad5a-66acff29f983
spec:
  conversion:
    strategy: None
  group: openappsec.io
  names:
    kind: SourcesIdentifier
    listKind: SourcesIdentifierList
    plural: sourcesidentifiers
    shortNames:
    - sourcesidentifier
    singular: sourcesidentifier
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            items:
              properties:
                sourceIdentifier:
                  enum:
                  - headerkey
                  - JWTKey
                  - cookie
                  - sourceip
                  - x-forwarded-for
                  type: string
                value:
                  items:
                    type: string
                  type: array
              type: object
            type: array
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: SourcesIdentifier
    listKind: SourcesIdentifierList
    plural: sourcesidentifiers
    shortNames:
    - sourcesidentifier
    singular: sourcesidentifier
  conditions:
  - lastTransitionTime: "2024-09-09T18:12:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-09-09T18:12:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
