apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2024-09-09T18:12:48Z"
  generation: 1
  name: policies.openappsec.io
  resourceVersion: "1365"
  uid: be06e52d-b787-4fe3-a6bd-820a69b8face
spec:
  conversion:
    strategy: None
  group: openappsec.io
  names:
    kind: Policy
    listKind: PolicyList
    plural: policies
    shortNames:
    - policy
    singular: policy
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              default:
                properties:
                  custom-response:
                    type: string
                  exceptions:
                    items:
                      type: string
                    type: array
                  mode:
                    enum:
                    - prevent-learn
                    - detect-learn
                    - prevent
                    - detect
                    - inactive
                    type: string
                  practices:
                    items:
                      type: string
                    type: array
                  source-identifiers:
                    type: string
                  triggers:
                    items:
                      type: string
                    type: array
                  trusted-sources:
                    type: string
                type: object
              specific-rules:
                items:
                  properties:
                    custom-response:
                      type: string
                    exceptions:
                      items:
                        type: string
                      type: array
                    host:
                      type: string
                    mode:
                      enum:
                      - prevent-learn
                      - detect-learn
                      - prevent
                      - detect
                      - inactive
                      type: string
                    practices:
                      items:
                        type: string
                      type: array
                    source-identifiers:
                      type: string
                    triggers:
                      items:
                        type: string
                      type: array
                    trusted-sources:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: Policy
    listKind: PolicyList
    plural: policies
    shortNames:
    - policy
    singular: policy
  conditions:
  - lastTransitionTime: "2024-09-09T18:12:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-09-09T18:12:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
