apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2024-09-09T18:12:48Z"
  generation: 1
  name: customresponses.openappsec.io
  resourceVersion: "1356"
  uid: abcc7a80-82e6-4e1b-90d1-1cefb38a1d26
spec:
  conversion:
    strategy: None
  group: openappsec.io
  names:
    kind: CustomResponse
    listKind: CustomResponseList
    plural: customresponses
    shortNames:
    - customresponse
    singular: customresponse
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              http-response-code:
                maximum: 599
                minimum: 100
                type: integer
              message-body:
                type: string
              message-title:
                type: string
              mode:
                enum:
                - block-page
                - response-code-only
                type: string
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: CustomResponse
    listKind: CustomResponseList
    plural: customresponses
    shortNames:
    - customresponse
    singular: customresponse
  conditions:
  - lastTransitionTime: "2024-09-09T18:12:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-09-09T18:12:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
